{
 "title": "Nodies",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "status", "label": "Status Code", "query": "label_values(status)" },
   { "name": "region", "label": "Region", "query": "label_values(region)" },
   { "name": "blockchain", "label": "Blockchain", "query": "label_values(blockchain)" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m" }
  ]
 },
 "panels": [
  { "title": "Top Agents and Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top User Agents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} | json http_user_agent [$__range]))",
     "legendFormat": "{{http_user_agent}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Top Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by (request, status) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} | json request [$__range])))",
     "legendFormat": "{{request}}:{{status}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(job) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(status) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Status Code",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(status) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Blockchain Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(blockchain) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Blockchain Node",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(blockchain) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Region",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(region) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$interval]))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Total Requests by Region",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(region) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} [$__range]))",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Codes by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(blockchain, region) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} | status = `401` [$interval]))",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    },
    {
     "title": "Error Codes by Blockchain and Region",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(blockchain, region) (count_over_time({job=\"varlogs\", region=~\"$region\", status=~\"$status\", blockchain=~\"$blockchain\"} | status = `401` [$__range]))",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Time by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg_over_time({job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json request_time | unwrap request_time | __error__=`` [$interval]) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    },
    {
     "title": "Request Time P50 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.50, {job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json request_time | unwrap request_time | __error__=`` [$interval]) by (blockchain, region) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    },
    {
     "title": "Request Time P90 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.90, {job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json request_time | unwrap request_time | __error__=`` [$interval]) by (blockchain, region) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Upstream Latency by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg_over_time({job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) by (blockchain, region) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    },
    {
     "title": "Upstream Latency P50 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.50, {job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) by (blockchain, region) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    },
    {
     "title": "Upstream Latency P90 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.90, {job=\"varlogs\", region=~\"$region\", status=~\"2\\\\d{2}\", blockchain=~\"$blockchain\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) by (blockchain, region) * 1000",
       "legendFormat": "{{blockchain}},{{region}}"
      }
     ]
    }
   ]
  }
 ]
}