{
 "title": "Chain Metrics (Blockchain Exporter)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "blockchain_id", "label": "Blockchain_ID", "query": { "query": "label_values(blockchain_id)" } },
   { "name": "endpoints", "label": "Endpoints", "query": { "query": "label_values(endpoint)" } }
  ]
 },
 "panels": [
  { "title": "$blockchain_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "blockchain_id" },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(endpoint) (max_over_time(sync_state{blockchain_id=~\"$blockchain_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Height Difference",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "Current Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "min by(endpoint) (current_height{blockchain_id=~\"$blockchain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max by(endpoint) (latest_height{blockchain_id=~\"$blockchain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}