{
 "title": "Pokt Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "status", "label": "Status Code", "query": "label_values(status)" },
   { "name": "regions", "label": "Regions", "query": { "query": "label_values(regions)" } },
   { "name": "chain_name", "label": "Blockchain", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "validator_address",
    "label": "Validator Address",
    "query": {
     "query": "label_values(validator_address)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Top Agents and Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top User Agents",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(http_user_agent) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} | json http_user_agent [$__range]))",
       "legendFormat": "{{http_user_agent}}",
       "resolution": 1
      }
     ]
    },
    {
     "title": "Top Endpoints",
     "type": "table",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "topk(10, sum by(request, status) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} | json request [$__range])))",
       "legendFormat": "{{request}}:{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(job) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(status) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Status Code",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(status) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Blockchain Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(chain_name) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Blockchain Node",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(chain_name) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Requests by Region",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(regions) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$interval]))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Total Requests by Region",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(regions) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} [$__range]))",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Codes by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(chain_name, regions) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} | status = `401` [$interval]))",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    },
    {
     "title": "Error Codes by Blockchain and Region",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(chain_name, regions) (count_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"$status\", chain_name=~\"$chain_name\"} | status = `401` [$__range]))",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Time by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(chain_name, regions) (avg_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json request_time | unwrap request_time | __error__=`` [$interval]) * 1000)",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    },
    {
     "title": "Request Time P50 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.50, {job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json request_time | unwrap request_time | __error__=`` [$interval]) by (chain_name, regions) * 1000",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    },
    {
     "title": "Request Time P90 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.90, {job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json request_time | unwrap request_time | __error__=`` [$interval]) by (chain_name, regions) * 1000",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Upstream Latency by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(chain_name, regions) (avg_over_time({job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) * 1000)",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    },
    {
     "title": "Upstream Latency P50 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.5, {job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) by (chain_name, regions)",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    },
    {
     "title": "Upstream Latency P90 by Blockchain and Region",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.9, {job=\"varlogs\", regions=~\"$regions\", status=~\"2\\\\d{2}\", chain_name=~\"$chain_name\"} | json upstream_response_time | unwrap upstream_response_time | __error__=`` [$interval]) by (chain_name, regions)",
       "legendFormat": "{{chain_name}},{{regions}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(delta(pocketcore_service_relay_count_for_all{regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Rate by Chain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum by(chain_name) (delta(pocketcore_service_relay_count{chain_name=~\"$chain_name\", regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(delta(pocketcore_service_avg_relay_time_sum{regions=~\"$regions\"}[$interval])) / sum(delta(pocketcore_service_avg_relay_time_count{regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency by Chain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by(chain_name, regions) (delta(pocketcore_service_avg_relay_time_sum{chain_name=~\"$chain_name\", regions=~\"$regions\"}[$interval])) / sum by(chain_name) (delta(pocketcore_service_avg_relay_time_count{chain_name=~\"$chain_name\", regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(delta(pocketcore_service_err_count_for_all{regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate by Chain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by(chain_name) (delta(pocketcore_service_err_count{chain_name=~\"$chain_name\", regions=~\"$regions\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}